sudo: required
services:
- docker
language: node_js
node_js:
- '8'
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - GH_REPO=redbox-mint-contrib/redbox2ckan
  - GIT_NAME=DeploymentBot
  - GIT_EMAIL=deploy@travis-ci.org
  - secure: TXtt5DVWklvY4ryOZcWFdC+BhC0v1hYxt4cR1DxPvK7bbn7N4ejY0bZIIxe1RwzvMiUNxw2USczbxgvJgyPQZ5qgr5o7PoGpAcK03u83Z7AJpFFp7kSZGZ1jmoF3OSIKZeYxrt+ZoqAANtIN3r4nAWvfnVFyjgvOxqauouinwL8avCOMM3X9Ml4fpBgHEy4+9/nH9DwyN1dFUbvYk//8Iiy9rggH/sStgILTq0bPogq9aonkPJVoMJK0R6aa8I4f+X778bmI7ini+EcELd1RPS036/hCPBLHkvtM+T4PVE3JXdRqPw9NY5flTScoYm06cFxKj4qoqVTBEAyho2sJxRibEPM6oDF9niinbdU9F3y19Q/nl8e1dTpn5NqmpVVyiYPn4pcPlxHtnZdX/R/kXy5mWzSLPMRbww7Jmh9cNEhgzK2LoWvQ8GbFSqP6CZNhyRBcIDRo21I4MG73+bv9Z90RZH0fs431t07kC0AJwG1cWzWADz0Yc4tq8Of+vTWyy8nFdJKFM4MoPHoXr6j/e5C++JuWc1qvtJkHWyeXxMGKpV2lsV3WO0iIljau7jn0+CZMhWFX4Z4IqVjB5KDRY+5mEP5peu2K8wG9VYY3vvXtQsgMBPiWnvXuQ2Cdn9xnXaG6YS1g1z87RixrC2DB8+YTk8iOAWRgn5LE9mAmLaI=
install:
- npm install; npm run distUtil
script: true
after_success:
- chmod +x deploySnapshotToBranch.sh; ./deploySnapshotToBranch.sh
